# Generated by Django 3.2.18 on 2023-04-15 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='ano',
            new_name='año',
        ),
        migrations.AddField(
            model_name='auto',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='dueño',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to='auth.user'),
            preserve_default=False,
        ),
    ]
